/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/places/autocomplete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Autocomplete */
        get: operations["autocomplete_places_autocomplete_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/places/cities/{place_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** City Location */
        get: operations["city_location_places_cities__place_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Results */
        get: operations["session_results_sessions__session_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Session */
        post: operations["search_session_sessions__session_id__search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CityLocation */
        CityLocation: {
            /** Formatted Address */
            formatted_address: string | null;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /** Place Id */
            place_id: string;
        };
        /** CityPrediction */
        CityPrediction: {
            /** Description */
            description: string;
            /** Place Id */
            place_id: string;
        };
        /** CreateSessionRequest */
        CreateSessionRequest: {
            /** Initial Query */
            initial_query: string;
            location?: components["schemas"]["LocationInput"] | null;
            /**
             * Mode
             * @enum {string}
             */
            mode: "solo" | "group";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LocationInput */
        LocationInput: {
            /** Formatted Address */
            formatted_address?: string | null;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /** Place Id */
            place_id?: string | null;
        };
        /**
         * RestaurantOut
         * @description User-facing details of one candidate; internal fields (scores, ids of members) stay out.
         */
        RestaurantOut: {
            /** Address */
            address: string;
            /** Cuisine */
            cuisine: string | null;
            /** Distance M */
            distance_m: number | null;
            /** Maps Uri */
            maps_uri: string | null;
            /** Name */
            name: string;
            /** Place Id */
            place_id: string;
            /** Price Level */
            price_level: number | null;
            /** Rating */
            rating: number | null;
            /** Rating Count */
            rating_count: number | null;
        };
        /**
         * ResultsResponse
         * @description All candidates, best first. The client shows the first 3, then the rest on request.
         */
        ResultsResponse: {
            /** Restaurants */
            restaurants: components["schemas"]["RestaurantOut"][];
        };
        /**
         * SearchRequest
         * @description The setup answers, sent in one call after the last setup page.
         */
        SearchRequest: {
            /**
             * After
             * @enum {string}
             */
            after: "breakfast" | "lunch" | "dinner" | "coffee_dessert" | "drinks";
            /**
             * Dietary
             * @default none
             * @enum {string}
             */
            dietary: "none" | "vegetarian" | "vegan" | "halal";
            /** Minutes */
            minutes: number;
            /**
             * Mode
             * @enum {string}
             */
            mode: "walk" | "drive";
            /**
             * Price Levels
             * @default []
             */
            price_levels: number[];
        };
        /** SearchResponse */
        SearchResponse: {
            /** Count */
            count: number;
        };
        /** SessionResponse */
        SessionResponse: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "solo" | "group";
            /** Session Id */
            session_id: string;
            /** Share Url */
            share_url: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    autocomplete_places_autocomplete_get: {
        parameters: {
            query: {
                input: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CityPrediction"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    city_location_places_cities__place_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                place_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CityLocation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_results_sessions__session_id__results_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_session_sessions__session_id__search_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
